### ISSUE TITLE
Error in running vdp.c (earlier version)

### ISSUE THREAD

**Issue by MohanaMadhumita** [MohanaMadhumita/Clarinet#8]
@nirajnsharma 
I have commented  #include_next  line and tried running again.
Below is the terminal output when i run the command in vdp directory
`make MAIN=vdp all`

/home/madhumita/x-tools/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc -march=rv32imafc -mabi=ilp32f -specs=bare.specs -g -DCLOCK_MHZ=71 -mcmodel=medlow -I../lib -DRV32   -c -o uart.o uart.c
uart.c:92:17: **error: unknown type name 'uint8_t'**
  const volatile uint8_t rbr;
                 ^~~~~~~
uart.c:93:11: **error: unknown type name 'uint8_t'**
  volatile uint8_t thr;
           ^~~~~~~
uart.c:94:11: error: **unknown type name 'uint8_t'**
  volatile uint8_t dll;
           ^~~~~~~
uart.c:99:11: error: **unknown type name 'uint8_t'**
  volatile uint8_t dlm;
           ^~~~~~~
uart.c:119:14: error: **unknown type name 'uint8_t'**
     volatile uint8_t msr __attribute__ ((aligned (4)));
              ^~~~~~~
uart.c:122:14: error: unknown type name 'uint8_t'
     volatile uint8_t scr __attribute__ ((aligned (4)));
              ^~~~~~~
uart.c: In function 'ns16550_init':
uart.c:130:5: error: unknown type name 'uint32_t'
     uint32_t divisor;
     ^~~~~~~~
<builtin>: **recipe for target 'uart.o' failed**
make: *** [uart.o] Error 1
`

**Comment by nirajnsharma** [comment]
Please paste the original error before you commented stuff. It is not able to recognize the hardware types which are defined in inttypes.h

**Comment by MohanaMadhumita** [comment]
/home/madhumita/x-tools/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc -march=rv32imafc -mabi=ilp32f -specs=bare.specs -g -DCLOCK_MHZ=71 -mcmodel=medlow -I../lib -DRV32   -c -o uart.o uart.c
In file included from uart.c:2:
/home/madhumita/x-tools/riscv32-unknown-elf/lib/gcc/riscv32-unknown-elf/8.3.0/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
 #include_next <stdint.h>
                ^~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'uart.o' failed
make: *** [uart.o] Error 1

**Comment by MohanaMadhumita** [comment]
![stdint_h](https://user-images.githubusercontent.com/28309245/97962786-e4498980-1ddb-11eb-889a-156669d260c2.png)

These were the codelines in stdint.h

**Comment by nirajnsharma** [comment]
No, I think we are following the wrong path in this debug. Let's get together on teamviewer tomorrow (does 3pm work for you)? Please do the following before our call. Make sure you have a ready installation of cross-tools and you have done the steps to add the clarinet new instructions by creating your own version of Binutils. Keep it separate from the default binutils-2.34.

**Comment by MohanaMadhumita** [comment]
Sure Niraj, I shall keep those ready before call. Tomorrow 3pm works. Thanks!

**Comment by MohanaMadhumita** [comment]
@nirajnsharma 
There are a few things I tried

**1.** After `ct-ng build` I have run the command `make TYPE=FLOAT MAIN=vdp all`
The terminal output says:
`/home/madhumita/x-tools/riscv32-unknown-elf/bin/riscv32-unknown-elf-gcc -march=rv32imafc -mabi=ilp32f -specs=bare.specs -g -DCLOCK_MHZ=71 -mcmodel=medlow -I../lib -DRV32   -c -o clarinet.o ../lib/clarinet.c
../lib/clarinet.c: Assembler messages:
../lib/clarinet.c:14: Error: unrecognized opcode `pmv.w.x ft0,a0'
../lib/clarinet.c:15: Error: unrecognized opcode `pmv.w.x ft1,a1'
../lib/clarinet.c:19: Error: unrecognized opcode `fma.p ft0,ft0,ft1'
../lib/clarinet.c:32: Error: unrecognized opcode `fcvt.p.s ft0,fa0'
../lib/clarinet.c:33: Error: unrecognized opcode `fcvt.p.s ft1,fa1'
../lib/clarinet.c:36: Error: unrecognized opcode `fma.p ft0,ft0,ft1'
../lib/clarinet.c:58: Error: unrecognized opcode `pmv.w.x ft1,a0'
../lib/clarinet.c:61: Error: unrecognized opcode `fcvt.r.p ft0,ft1'
../lib/clarinet.c:69: Error: unrecognized opcode `fcvt.p.s ft1,fa0'
../lib/clarinet.c:72: Error: unrecognized opcode `fcvt.r.p ft0,ft1'
../lib/clarinet.c:79: Error: unrecognized opcode `fcvt.p.r f0,f0'
../lib/clarinet.c:80: Error: unrecognized opcode `pmv.x.w a0,f0'
../lib/clarinet.c:87: Error: unrecognized opcode `fcvt.p.r f0,f0'
../lib/clarinet.c:88: Error: unrecognized opcode `fcvt.s.p fa0,f0'
<builtin>: recipe for target 'clarinet.o' failed
make: *** [clarinet.o] Error 1
`
**2.** I found a few options in the menuconfig GUI to use custom binutilts folder. I have included binutils-2.34(not including Clarinet opcodes) folder and could succesfully run `ct-ng` build.

**3.** Then, I included Clarinet opcodes and running `ct-ng` build gives me the following in the terminal.
`
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    configure: error: source directory already configured; run "make distclean" there first
[ERROR]    make[2]: *** [configure-zlib] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@213]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@70]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 3:16.74)
[03:18] / /home/madhumita/tools/bin/ct-ng:261: recipe for target 'build' failed
make: *** [build] Error 2


Can you help where I'm going wrong?
`

**Comment by nirajnsharma** [comment]
Okay, let's break this up. The first result is encouraging (maybe I was wrong about `TYPE=FLOAT` being able to avoid *all* Clarinet new instructions). What your first result means (the one with FLOAT) is that your first `ct-ng build` with default archives is good.

Now points 2 and 3 are I think to do with ct-ng usage. Here's what I suggest. I am sharing my .config with this note. Please look at lines 45-59 and use it to configure the same section in your .config. Place all the tar balls in some directory of your choice which is outside the .build directory and make sure that path is also there in your .config (line 47 in my .config).

Replace the original binutils with your binutils (the one with Clarinet modifications) in that directory. Remove the old .build and any build.log and rerun `ct-ng build`

**Comment by MohanaMadhumita** [comment]
I didn't receive the .config file. Can you please resend?

**Comment by nirajnsharma** [comment]
Sorry, forgot to attach in the issue. Here it is.

**Comment by MohanaMadhumita** [comment]
There was some progress yesterday, I cleaned up everything and retried doing the explicit tarball location. 
1. Afer succesfully building toolchain using `ct-ng build` , I've run `make TYPE=FLOAT MAIN=vdp all` and could generate a `vdp.dump` and `vdp executable` file. So I hope, the toolchain is up and running.
2. Then I ran `./vdp` , the terminal gives
`bash: ./vdp: cannot execute binary file: Exec format error`
How do we run the generated executable file?

**Comment by nirajnsharma** [comment]
The `./vdp` you just created is *not* an x86 binary, which is why you cannot run it natively on your x86 computer. It was created through a process called *cross-compilation*, where you run the compiler for another architecture (here RV32) on a computer running an OS in a different architecture (here x86). Since two architectures are involved, it's called *cross* compilation. 

To run `vdp` you have to load the contents of the binary into the memory of the clarinet processor. For now, this is done through a RTL simulation of the Clarinet processor. In general what you are doing is booting up the Clarinet processor using a bare-metal (no OS) platform and loading `vdp` to run on that platform. 

Now, with that background, go to your build directory under `clarinet/builds/RV32...`. There run the command:

`make run_example EXAMPLE=/path/to/vdp/binary`

This will load the binary into Clarinet's memory, reset the processor and set PC to the beginning of your program.

**Comment by MohanaMadhumita** [comment]
1. Running the command `make run_example EXAMPLE=/home/bsc/Clarinet/applications/vdp/vdp/binary`, asked to install a few libraries. Later it gave out the following on terminal. 
`
make run_example EXAMPLE=/home/bsc/Clarinet/applications/vdp/vdp/binary
make -C  ../../Tests/elf_to_hex
make[1]: Entering directory '/home/madhumita/bsc/Clarinet/Tests/elf_to_hex'
make[1]: 'elf_to_hex' is up to date.
make[1]: Leaving directory '/home/madhumita/bsc/Clarinet/Tests/elf_to_hex'
../../Tests/elf_to_hex/elf_to_hex  /home/bsc/Clarinet/applications/vdp/vdp/binary  Mem.hex
ERROR: c_mem_load_elf: could not open elf input file: /home/bsc/Clarinet/applications/vdp/vdp/binary
../../builds/Resources/Include_Common.mk:89: recipe for target 'run_example' failed
make: *** [run_example] Error 1
`
No elf file was generated using any Makefile.

**Comment by nirajnsharma** [comment]
Does `/home/bsc/Clarinet/applications/vdp/vdp/binary` exist? Is it a RISC-V elf file?

**Comment by MohanaMadhumita** [comment]
Oh..binary doesn't exist. I have checked the hidden files too. No such file

**Comment by nirajnsharma** [comment]
That path should be the path to the elf file you generated by compiling the vdp program. In my example, the path I gave was just a placeholder. Put the path to the actual RISC-V elf you created by running riscv32-unknown-elf-gcc (the make command from the vdp directory).
